### ISSUE TITLE
Alpine linux 3.15 on pypy3 test_52_numeric_ops_float fails

### ISSUE THREAD

**Issue by sundarnagarajan** [sundarnagarajan/python_protected_class#4]
```
ERROR: test_52_numeric_ops_float (__main__.test_pyprotect)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_pyprotect.py", line 1137, in test_52_numeric_ops_float
    assert(ceil(w1) == 101)
  File "Proxy.pxi", line 114, in pyprotect.protected.Proxy.__ceil__
AttributeError: 'CF' object has no attribute '__ceil__'. Did you mean: __bool__?
```

Not yet ivnestigated.
The same test does not fail on pypy3 on ubuntu jammy

**Comment by sundarnagarajan** [comment]
Temporarily worked around by not executing this test on PYPY3

**Comment by sundarnagarajan** [comment]
Implemented (more) correct answer in pyprotct/Proxy.pxi: c127f2a

```patch
--- a/pyprotect/Proxy.pxi
+++ b/pyprotect/Proxy.pxi
@@ -108,10 +108,10 @@ cdef class Proxy(object):
         return self.pvt_o.__trunc__()
 
     def __floor__(self):
-        return self.pvt_o.__floor__()
+        return math.floor(self.pvt_o)
 
     def __ceil__(self):
-        return self.pvt_o.__ceil__()
+        return math.ceil(self.pvt_o)
```

Keeping this issue open.

This is a surprising behavior in __pypy3__, and a behavior that specifically manifests on Alpine Linux (and not Ubuntu). This cannot be written off as "Python2 - will not fix".
